import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Plain-markdown project memory under `.vovy/memory/`, committed to git.
 *
 * Git is the whole backend: memory travels with `git clone` into every host Vovy supports,
 * a teammate gets it for free, and entries are reviewable in PRs. No server, no account,
 * nothing to meter — the same free-forever constraint as everything else here. Recall is
 * deterministic keyword scoring, NOT embeddings: computing embeddings is LLM inference,
 * which the constraint rules out (see docs/architecture.md).
 */

export type MemoryType = "decision" | "mistake" | "constraint";

export const MEMORY_TYPES: MemoryType[] = ["decision", "mistake", "constraint"];

export interface MemoryEntry {
  type: MemoryType;
  title: string;
  /** Markdown body. House structure (enforced by the memory-keeper skill, not by code):
   * decisions record what was rejected and why; mistakes record why it happened and how
   * to avoid it; constraints record the why behind the rule. */
  body: string;
  tags: string[];
  /** ISO date the entry was recorded or last updated. */
  date: string;
  /** Repo-relative path of the file holding this entry. */
  file: string;
}

export interface RecallMatch extends MemoryEntry {
  score: number;
}

const MEMORY_DIR = join(".vovy", "memory");

/**
 * Obvious credential shapes. Memory files are committed to git — for the founders Vovy
 * targets, silently writing a key into a repo that may be public is exactly the class of
 * mistake `founder-explainer` exists to catch, so `record` refuses outright rather than
 * warns. Deterministic patterns only; this is a tripwire, not a scanner.
 */
const SECRET_PATTERNS: Array<{ pattern: RegExp; looksLike: string }> = [
  { pattern: /sk-[A-Za-z0-9_-]{16,}/, looksLike: "an API key (sk-...)" },
  { pattern: /AKIA[0-9A-Z]{16}/, looksLike: "an AWS access key" },
  { pattern: /gh[pousr]_[A-Za-z0-9]{30,}/, looksLike: "a GitHub token" },
  { pattern: /-----BEGIN [A-Z ]*PRIVATE KEY-----/, looksLike: "a private key" },
  { pattern: /eyJ[A-Za-z0-9_-]{20,}\.eyJ/, looksLike: "a JWT" },
];

export function findSecret(text: string): string | null {
  for (const { pattern, looksLike } of SECRET_PATTERNS) {
    if (pattern.test(text)) return looksLike;
  }
  return null;
}

function slugify(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "untitled"
  );
}

/** Same minimal frontmatter shape as @vovy-ai/skills' SKILL.md parser — duplicated
 * rather than shared, since skills doesn't export its parser and a dependency for 15
 * lines isn't worth the coupling. */
function parseEntry(raw: string, file: string): MemoryEntry | null {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) return null;
  const [, frontmatter, body] = match;
  const fields: Record<string, string> = {};
  for (const line of (frontmatter ?? "").split(/\r?\n/)) {
    const fieldMatch = line.match(/^([a-zA-Z_-]+):\s*(.*)$/);
    if (fieldMatch?.[1]) fields[fieldMatch[1]] = (fieldMatch[2] ?? "").trim();
  }
  const type = fields.type as MemoryType;
  if (!MEMORY_TYPES.includes(type) || !fields.title) return null;
  return {
    type,
    title: fields.title,
    body: (body ?? "").trim(),
    tags: fields.tags
      ? fields.tags
          .split(",")
          .map((t) => t.trim())
          .filter(Boolean)
      : [],
    date: fields.date ?? "",
    file,
  };
}

export function listMemory(root: string): MemoryEntry[] {
  const entries: MemoryEntry[] = [];
  for (const type of MEMORY_TYPES) {
    const dir = join(root, MEMORY_DIR, `${type}s`);
    if (!existsSync(dir)) continue;
    for (const name of readdirSync(dir).sort()) {
      if (!name.endsWith(".md")) continue;
      const file = join(MEMORY_DIR, `${type}s`, name);
      try {
        const entry = parseEntry(readFileSync(join(root, file), "utf8"), file);
        if (entry) entries.push(entry);
      } catch {
        // An unreadable or malformed entry is skipped, not fatal — same best-effort
        // convention as the rest of the codebase.
      }
    }
  }
  return entries;
}

function regenerateIndex(root: string): void {
  const lines = listMemory(root).map(
    (e) => `- **${e.type}** [${e.title}](${e.file.replace(`${MEMORY_DIR}/`, "")}) — ${e.date}`,
  );
  const content = `# Project memory index

One line per entry — regenerated by \`project_memory\` on every record, do not edit by hand.
Read an entry's file for the full rationale.

${lines.join("\n")}
`;
  writeFileSync(join(root, MEMORY_DIR, "INDEX.md"), content);
}

export interface RecordResult {
  action: "created" | "updated";
  file: string;
}

export function recordMemory(
  root: string,
  input: { type: MemoryType; title: string; body: string; tags?: string[] },
): RecordResult {
  const secret = findSecret(`${input.title}\n${input.body}`);
  if (secret) {
    throw new Error(
      `Refusing to record: the content contains what looks like ${secret}. .vovy/memory/ is committed to git — a secret recorded here can end up public. Remove the credential and describe it instead (e.g. 'the Stripe key in .env').`,
    );
  }

  const dir = join(root, MEMORY_DIR, `${input.type}s`);
  mkdirSync(dir, { recursive: true });

  const slug = slugify(input.title);
  const file = join(dir, `${slug}.md`);
  const action: RecordResult["action"] = existsSync(file) ? "updated" : "created";

  const frontmatter = [
    "---",
    `type: ${input.type}`,
    `title: ${input.title}`,
    `date: ${new Date().toISOString().slice(0, 10)}`,
    ...(input.tags?.length ? [`tags: ${input.tags.join(", ")}`] : []),
    "---",
    "",
  ].join("\n");
  writeFileSync(file, `${frontmatter}${input.body.trim()}\n`);

  regenerateIndex(root);
  return { action, file: join(MEMORY_DIR, `${input.type}s`, `${slug}.md`) };
}

const STOP_WORDS = new Set([
  "the",
  "a",
  "an",
  "this",
  "that",
  "to",
  "of",
  "in",
  "is",
  "it",
  "and",
  "or",
  "for",
  "we",
  "was",
  "with",
  "on",
  "not",
  "do",
  "did",
  "why",
  "how",
  "what",
  "when",
]);

function contentWords(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((w) => w.length > 2 && !STOP_WORDS.has(w));
}

/**
 * Deterministic keyword recall — title hits weigh most, then tags, then body. The same
 * kind of scorer as @vovy-ai/skills' `matchSkills`, and honest about what it is: word
 * overlap, not semantic search. For the few hundred entries a project accumulates, that
 * is enough, and it costs no model call.
 */
export function recallMemory(root: string, query: string, limit = 5): RecallMatch[] {
  const queryWords = new Set(contentWords(query));
  if (queryWords.size === 0) return [];

  return listMemory(root)
    .map((entry) => {
      const titleWords = new Set(contentWords(entry.title));
      const tagWords = new Set(entry.tags.flatMap((t) => contentWords(t)));
      const bodyWords = new Set(contentWords(entry.body));
      let score = 0;
      for (const word of queryWords) {
        if (titleWords.has(word)) score += 3;
        if (tagWords.has(word)) score += 2;
        if (bodyWords.has(word)) score += 1;
      }
      return { ...entry, score };
    })
    .filter((m) => m.score > 0)
    .sort((a, b) => b.score - a.score || a.title.localeCompare(b.title))
    .slice(0, limit);
}
